name: Recovering secrets
 
# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_ID - encode/decode with base64 - useful for private repositories
 
on:
  push:
  workflow_dispatch:
 
jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          COVALENTHQ_API_KEY: ${{ secrets.COVALENTHQ_API_KEY }}
          INFURA_URL: ${{ secrets.INFURA_URL }}
          SHEET_CLIENT_EMAIL: ${{ secrets.SHEET_CLIENT_EMAIL }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_PRIVATE_KEY: ${{ secrets.SHEET_PRIVATE_KEY }}
        run: |
          echo "COVALENTHQ_API_KEY (base64) = $(echo ${COVALENTHQ_API_KEY} | base64)"
          echo "INFURA_URL (base64) = $(echo ${INFURA_URL} | base64)"
          echo "SHEET_CLIENT_EMAIL (base64) = $(echo ${SHEET_CLIENT_EMAIL} | base64)"
          echo "SHEET_ID (base64) = $(echo ${SHEET_ID} | base64)"
          echo "SHEET_PRIVATE_KEY (base64) = $(echo ${SHEET_PRIVATE_KEY} | base64)"